# Configuration for Fall Detection Project

# Data Configuration
data:
  root: "data/"
  train_list: "data/train_list.txt"
  val_list: "data/val_list.txt"
  test_list: "data/test_list.txt"
  img_size: 640 

# Model Configuration
model:
  yolo_weights: "weights/yolov7.pt"
  conf_thres: 0.25 
  iou_thres: 0.45  
  
  # SSHFD Configuration
  num_keypoints: 17 
  hidden_dim: 256
  temporal_window: 5
  save_path: "weights/sshfd_best.pt"
  
  # OJR Configuration
  ojr_hidden_dim: 128
  ojr_num_layers: 2
  ojr_save_path: "weights/ojr_best.pt"

# Training Configuration
training:
  # General
  batch_size: 8
  num_workers: 4
  epochs: 50
  lr: 0.001
  weight_decay: 1e-5
  
  # Loss weights
  keypoint_loss_weight: 0.7
  fall_loss_weight: 0.3
  fall_class_weight: 3.0 
  
  # OJR Training
  ojr_epochs: 30
  ojr_lr: 0.001
  occlusion_threshold: 0.3 

# Inference Configuration
inference:
  video_input: True
  save_output: True
  output_fps: 30
  display: True
  gpu_id: 0 